//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_sales
    {
        public int Transaction_no { get; set; }
        public string product_id { get; set; }
        public int Sales_id { get; set; }
        public string Product_Name { get; set; }
        public decimal purchase_price { get; set; }
        public int Quantity { get; set; }
        public decimal ItemTotal { get; set; }
    
        public virtual product product { get; set; }
        public virtual sales_order sales_order { get; set; }
    }
}
