//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_sales = new HashSet<product_sales>();
            this.product_purchase = new HashSet<product_purchase>();
        }
    
        public string ProductID { get; set; }
        public string Name { get; set; }
        public decimal Sales_Price { get; set; }
        public decimal Purchase_Price { get; set; }
        public int SupplierID { get; set; }
        public string Product_Type { get; set; }
        public string Size { get; set; }
        public string Brand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_sales> product_sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_purchase> product_purchase { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
