//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales_order()
        {
            this.product_sales = new HashSet<product_sales>();
        }
    
        public int SaleID { get; set; }
        public int customer { get; set; }
        public decimal Total { get; set; }
        public decimal Discount { get; set; }
        public decimal Sub_Total { get; set; }
    
        public virtual customer customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_sales> product_sales { get; set; }
    }
}
